site_name: test mkdocs master site
site_url: https://github.com/jay-m-dev/test-mkdocs-master

repo_url: https://github.com/jay-m-dev/test-mkdocs-master
edit_uri: edit/master/docs_sources/
docs_dir: docs_sources/
site_dir: docs/
theme: readthedocs

nav:
  - Home: index.md
